**STEP 1: Simulation**

In [1]:
import numpy as np
from scipy.stats import norm
def simulate_matrix(n, d, density, out_fra, corr):
    # Generate a simulated large-scale matrix ~ N(0,1)
    X = np.random.normal(loc=0, scale=1, size=(n, d))

    # Apply corr structure with normal distribution
                                       
    # Set the correlation strength to be the desired value
    corr_strength = corr
    # scaling the values in X with strength
    XX = X * corr_strength
    # Add noise to the correlation values
    XX = XX + np.random.normal(0,1-corr_strength**2,size=(n,d))
    # transform X to be correlated
    X = norm.cdf(XX)

    # Apply nonlinear by using ReLU Function
    X = np.maximum(0,X)

    # To sparse matrix by setting the desired fraction to be zero (out of density)
    X[np.random.rand(n, d) > density] = 0

    # Add outliers by randomly selecting rows and adding 10 times entities ~ N(0,1)

    ### size of outliers
    size = int(out_fra * n)
    outlier_idx = np.random.choice(n, size=size, replace=False)
    X[outlier_idx] += 39 * np.random.normal(loc=0, scale=1, size=(size, d))

    return X

# Matrix Settled
n = 5000       # number of rows         
d = 100        # number of columns
density = 0.87  # sparse density to make more 0 entities
out_fra = 0.2  # outliers' fraction
corr = 0.15    # correlation strength

X = simulate_matrix(n, d, density, out_fra, corr) # A matrix
Y = np.random.normal(loc=0,scale=1,size=(n,1)) # b vector
print("The simulated matrix is:")
print(np.array(X))
print("The number of 0 entities' ratio is:",int((X==0).sum())/(n*d))

The simulated matrix is:
[[0.62384917 0.70385847 0.53048082 ... 0.51490794 0.99555834 0.22426993]
 [0.06881836 0.47624139 0.         ... 0.32276488 0.29737352 0.3196222 ]
 [0.98271761 0.27563214 0.19715767 ... 0.43363418 0.77850941 0.51251404]
 ...
 [0.45099727 0.         0.21654176 ... 0.         0.32447757 0.18565653]
 [0.19773887 0.1029887  0.2626155  ... 0.9858306  0.         0.00278915]
 [0.6781432  0.66435756 0.11550641 ... 0.67731678 0.21918726 0.1755725 ]]
The number of 0 entities' ratio is: 0.103928


*Define functions for calculating ratio and norms*

In [2]:
def calculate_the_norm(A,b,x_selected):
    return (np.linalg.norm(A @ x_selected - b)) ** 2
def abs_error_ratio(A,b,x_hat_bar,x_star):
    return abs(calculate_the_norm(A,b,x_hat_bar) - calculate_the_norm(A,b,x_star)) / calculate_the_norm(A,b,x_star)