In [1]:
import numpy as np
from scipy.linalg import hadamard

# float32 (fast, light) — good default
H4     = hadamard(4).astype(np.float32) / np.sqrt(4, dtype=np.float32)
H2048  = hadamard(2048).astype(np.float32) / np.sqrt(2048, dtype=np.float32)
print(H4)
print(H2048)

[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]
[[ 0.02209709  0.02209709  0.02209709 ...  0.02209709  0.02209709
   0.02209709]
 [ 0.02209709 -0.02209709  0.02209709 ... -0.02209709  0.02209709
  -0.02209709]
 [ 0.02209709  0.02209709 -0.02209709 ...  0.02209709 -0.02209709
  -0.02209709]
 ...
 [ 0.02209709 -0.02209709  0.02209709 ...  0.02209709 -0.02209709
   0.02209709]
 [ 0.02209709  0.02209709 -0.02209709 ... -0.02209709  0.02209709
   0.02209709]
 [ 0.02209709 -0.02209709 -0.02209709 ...  0.02209709  0.02209709
  -0.02209709]]
