In [1]:
import numpy as np
from scipy.stats import norm
def simulate_matrix(n, d, density, out_fra, corr):
    # Generate a simulated large-scale matrix ~ N(0,1)
    X = np.random.normal(loc=0, scale=1, size=(n, d))

    # Apply corr structure with normal distribution                                             
    # Set the correlation strength to be the desired value
    corr_strength = corr
    # scaling the values in X with strength
    XX = X * corr_strength
    # Add noise to the correlation values
    XX = XX + np.random.normal(0,1-corr_strength**2,size=(n,d))
    # transform X to be correlated
    X = norm.cdf(XX)
    # Apply nonlinear by using ReLU Function
    X = np.maximum(0,X)
    # To sparse matrix by setting the desired fraction to be zero (out of density)
    X[np.random.rand(n, d) > density] = 0

    # Add outliers by randomly selecting rows and adding 10 times entities ~ N(0,1)
    ### size of outliers
    size = int(out_fra * n)
    outlier_idx = np.random.choice(n, size=size, replace=False)
    X[outlier_idx] += 39 * np.random.normal(loc=0, scale=1, size=(size, d))

    return X

# Example usage
n = 5000       # number of rows         
d = 100        # number of columns
density = 0.85  # sparse density to make more 0 entities
out_fra = 0.2  # outliers' fraction
corr = 0.15    # correlation strength

X = simulate_matrix(n, d, density, out_fra, corr)
Y = np.random.normal(loc=0,scale=1,size=(n,1))
print("The simulated matrix is:")
print(X)
print("The number of 0 entities is:",int((X==0).sum()))

The simulated matrix is:
[[0.04629876 0.         0.         ... 0.52597024 0.39774833 0.29466658]
 [0.         0.63067371 0.         ... 0.         0.75774313 0.16601024]
 [0.06083258 0.95759619 0.05465896 ... 0.33206994 0.24451917 0.15070168]
 ...
 [0.22235383 0.38934161 0.         ... 0.         0.76980797 0.74159216]
 [0.93474501 0.74870563 0.45417252 ... 0.06198813 0.92184371 0.77003869]
 [0.265936   0.33614308 0.82263917 ... 0.20858451 0.2184608  0.7730728 ]]
The number of 0 entities is: 60302
