In [1]:
import numpy as np
from scipy.stats import norm
def simulate_matrix(n, d, density, out_fra, corr):
    # Generate a simulated large-scale matrix ~ N(0,1)
    X = np.random.normal(loc=0, scale=1, size=(n, d))

    # Apply corr structure with normal distribution                                             
    # Set the correlation strength to be the desired value
    corr_strength = corr
    # scaling the values in X with strength
    XX = X * corr_strength
    # Add noise to the correlation values
    XX = XX + np.random.normal(0,1-corr_strength**2,size=(n,d))
    # transform X to be correlated
    X = norm.cdf(XX)
    # Apply nonlinear by using ReLU Function
    X = np.maximum(0,X)
    # To sparse matrix by setting the desired fraction to be zero (out of density)
    X[np.random.rand(n, d) > density] = 0

    # Add outliers by randomly selecting rows and adding 10 times entities ~ N(0,1)
    ### size of outliers
    size = int(out_fra * n)
    outlier_idx = np.random.choice(n, size=size, replace=False)
    X[outlier_idx] += 39 * np.random.normal(loc=0, scale=1, size=(size, d))

    return X

# Example usage
n = 5000       # number of rows         
d = 100        # number of columns
density = 0.85  # sparse density to make more 0 entities
out_fra = 0.2  # outliers' fraction
corr = 0.15    # correlation strength

X = simulate_matrix(n, d, density, out_fra, corr)
Y = np.random.normal(loc=0,scale=1,size=(n,1))
print("The simulated matrix is:")
print(X)
print("The number of 0 entities is:",int((X==0).sum()))

The simulated matrix is:
[[0.46296496 0.91443744 0.         ... 0.         0.         0.10314997]
 [0.94434192 0.26738379 0.59905169 ... 0.09193988 0.         0.72004891]
 [0.6978371  0.04508696 0.31313686 ... 0.91339406 0.12050044 0.76597686]
 ...
 [0.88454504 0.57634007 0.03504213 ... 0.51603808 0.58514591 0.84014708]
 [0.6121229  0.75730262 0.25278352 ... 0.81868713 0.         0.        ]
 [0.2084132  0.16972016 0.51109707 ... 0.89686411 0.         0.0993436 ]]
The number of 0 entities is: 60408
